name: arna_response_validation
description: Arna Response Validation is a simple and powerful HTTP validator for Flutter.
homepage: https://github.com/MahanRahmati/arna_response_validation
version: 1.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
